### ISSUE TITLE
Support more architectures (via sentry cli) 

### ISSUE THREAD

**Issue by StefMa** [ioki-mobility/SentryProguardGradlePlugin#68]
Currently we are only supporting MacArm and LinuxX86 because of the cli we download.
Actually there are more cli types available to download... We should do that.

**Comment by Fabi755** [comment]
Similar to https://github.com/ioki-mobility/LokaliseGradlePlugin/issues/24 I would suggest to use some API calls instead of using binaries.

**Comment by StefMa** [comment]
There is no api 😭
